“I want to be able to read newspapers and stay updated about the current affairs”, “I feel so contextually unaware of my surroundings”. These were some of the musings of the visually challenged at a session at the National Association for the Blind (NAB). I was at the venue on a visit to the organization and that day I responded rather strongly, tears welling up in my eyes, my mind dwelling on the challenges they had to face on a daily basis. The inspiration for research in Computer vision as an assistive technology for the visually impaired began there. My inherent affinity for programming and software and the endless potential of technology to provide solutions to pressing problems has resulted in undiluted passion for the field. 

Soon after this incident, I approached a renowned professor and simultaneously got together with a few classmates and formed a team to take up the cause of developing an enabling tool which would help the visually challenged on some level. We designed an inexpensive wearable device that uses computer vision along with some hardware like a Raspberry Pi to read out any form of text and enumerate objects around the user in various alignments and lighting conditions. An overall accuracy of 94% was achieved. My major contribution to the endeavor was decreasing the processing time by about 12 percent, using the concept of threads. Though the team had no major grasp of the concepts and principles of Computer vision, we took on the challenge of leaning relevant technologies and successfully completed the project. When tested on many blind individuals, the response was excellent and they found it to be a useful prototype.
The team was awarded with a number of awards, including the ‘Student Project Recognition Award – 2018’ from the Institute for Exploring Advances in Science & Engineering (IEAE) and ‘The Best Project of the Year’ recognition by the alumni association in college. To add to all of these accolades we published our project as a research paper at the ICACCI conference conducted by IEEE in Bangalore. The experience was an endless series of positive outcomes and being linked to a noble cause of major social relevance created a deep sense of gratification amongst the team members. 

Keen to apply learning and assimilate practical skills, I interned at Intel Technology India and Volvo India, where I not only got a hands-on experience on Data Modelling and AngularJs, but also learnt how to interact with people in a huge organization. Completing the undergraduate course with a CGPA of 9.39 and being the top 5 percentile made it even easier to be placed as a Software Engineer at JP Morgan Chase and Co. In the few months I have been in a professional role I could showcase my technical and problem-solving abilities, build further on presentation skills, team building, and communication.

I wish to capitalize on the high momentum through the Bachelors program and enroll in a graduate degree which will help bring specialized technical knowledge in majors and the skills to build exceptional customized solutions My choice of institution for a Master’s program in Computer Science is Georgia Institute of Technology which has on its faculty list awarded professors such as Prof. Quanquan Go and Prof. Cho-Jui Hseich. The strong research orientation at Centre for Vision, Cognition Learning and Antinomy (VCLA) and its objective is a major draw.  I hope to assist on faculty led projects and achieve greater clarity as regards my own thesis and future academic goals. With challenging coursework and the intensive research designs of cross-disciplinary teams, alignment to most contemporary questions and experimental conditions will be a given. I believe that my excellent academic skills, the ability to pursue and realize unique ideas, and readiness for challenges, make me deserving of a world class higher learning program at your school.

